name: Todo-app

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World"

  goodbye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Goodbye World
        run: echo "Goodbye"
